#!/bin/sh

datafiles=$(ls kv-committing-regbench-n-t*.data | grep -v combined)
singles="no"

if false ;then
    scales="500 1000 1500 2000 5000 10000 25000"
    style="linear"
else
    scales="0.125 0.25 0.5 1 2 4 8 16 32"
    scales="0.125 0.25 0.5"
    style="log"
fi

for scale in $scales ;do
    if [ "$singles" == "yes" ] ;then
	for df in $datafiles ; do
	    outfile=$(echo $df | sed s/.data/-${scale}-combined.data/)
	    combine-data.rb $style $scale $df > $outfile
	done
    fi
    combine-data.rb $style $scale $datafiles > kv-committing-regbench-n-tmulti-${scale}-combined.data
done
