#!/bin/sh

datafiles=$(ls kv-committing-regbench-n-t*.data | grep -v combined)

if false ; then
    for scale in 500 1000 1500 2000 5000 10000 25000; do
	outfiles=""
	for df in $datafiles ; do
	    outfile=$(echo $df | sed s/.data/-${scale}-combined.data/)
	    outfiles="$outfiles $outfile"
	    combine-data.rb linear $scale $df > $outfile
	done
	combine-data.rb linear $scale $datafiles > kv-committing-regbench-n-tmulti-${scale}-combined.data
    done
else
    for scale in 0.125 0.25 0.5 1 2 4 8 16 32 ; do
	outfiles=""
	for df in $datafiles ; do
	    outfile=$(echo $df | sed s/.data/-${scale}-combined.data/)
	    outfiles="$outfiles $outfile"
	    combine-data.rb log $scale $df > $outfile
	done
	combine-data.rb log $scale $datafiles > kv-committing-regbench-n-tmulti-${scale}-combined.data
    done
fi
