#!/bin/bash

logpath='out/osd*log'

if [ $# -lt 1 ] ; then
   echo "Usage: $0 key [logfiles]"
   exit 1
elif [ $# -eq 2 ] ;then
   logpath="$2"
fi

key=$1
out="kv-committing-${key}.data"

echo "# kv committing data" > $out
echo "# 1:osd 2:max_latency_nsec 3:kv_committing_count 4:total_ops 5:total_bytes 6:mean_ops 7:mean_bytes 8:early_ops_queue_size 9:early_bytes_queue_size 10:early_wal_ops_queue_size 11:early_wal_bytes_queue_size 12:late_ops_queue_size 13:late_bytes_queue_size 14:late_wal_ops_queue_size 15:late_wal_bytes_queue_size 16:time_to_commit_nsec 17:avg_latency_nsec 18:max_aio_time_latency 19:mean_aio_time_latency 20:throughput_bytes_per_second" >> $out

for f in $logpath ; do
    osd=$(echo $f | sed 's/.*osd\.\(.*\)\.log/\1/')
    grep kv_committing_data $f | \
    	 sed 's/.*kv_committing_data (\(.*\))$/\1/' | \
    	 sed 's/,/ /g' | \
	 sed "s/\(.*\)/${osd} \1/"
done >> $out
