#!/bin/sh

throttles2="11585"
throttles="4096 8192 16384 32768 65536 131072 262144 524288"

for t in $throttles ; do
    file="rb-lat-t${t}.data"
    echo "# throttle $t" > $file
    for c in 1 2 4 8 16 32 64 128 ; do
	dataf="throttle-${t}/regbench-summary-t${t}-o-c${c}.txt"
	avg_lat=$(grep 'Average Latency' $dataf | sed 's/.* //')
	stddev_lat=$(grep 'Stddev Latency' $dataf | sed 's/.* //')
	echo "$c $avg_lat $stddev_lat" >> $file
    done
done
