#!/bin/sh

throttles="4096 8192 16384 32768 65536 131072 262144 524288"

for t in $throttles ; do
    file="rb-thru-t${t}.data"
    echo "# throttle $t avg stddev in MB/sec" > $file
    for c in 1 2 4 8 16 32 64 128 ; do
	dataf="throttle-${t}/regbench-summary-t${t}-o-c${c}.txt"
	avg_lat=$(grep '^Bandwidth' $dataf | sed 's/.* //')
	stddev_lat=$(grep '^Stddev Bandwidth' $dataf | sed 's/.* //')
	echo "$c $avg_lat $stddev_lat" >> $file
    done
done
