#!/bin/sh

locate_build() {
  if pwd | grep -q ceph-work ; then
    echo ~/ceph-work/build
  elif pwd | grep -q ceph-master ; then
    echo ~/ceph-master/build
  else
    echo Please run this from one of the known build directories.
    exit 1
  fi
}
