#!/bin/sh

locate_build() {
  if pwd | egrep -q "/build(/.*)?$" ;then
      pwd | sed 's|\(.*/build\)\(/.*\)\?$|\1|'
      exit 0
  else
      >&2 echo "Error: not recognized as a build directory."
      exit 1
  fi
}
