#!/bin/sh

prologue=/tmp/plot-prologue.$$

cat >$prologue <<EOF
    set style line 1 pt 1 ps 1 lc "#66c2a5" lw 2
    set style line 2 pt 1 ps 1 lc "#fc8d62" lw 2
    set style line 3 pt 1 ps 1 lc "#8da0cb" lw 2
    set style line 4 pt 1 ps 1 lc "#e78ac3" lw 2
    set style line 5 pt 1 ps 1 lc "#a6d854" lw 2
    set style line 6 pt 1 ps 1 lc "#ffd92f" lw 2
    set style line 7 pt 1 ps 1 lc "#e5c494" lw 2
    set style line 8 pt 1 ps 1 lc "#b3b3b3" lw 2
    set style line 9 pt 1 ps 1 lc "#ffbbbb" lw 1
    set style line 10 pt 1 ps 1 lc "#bbffbb" lw 1
    set style line 11 pt 1 ps 1 lc "#bbbbff" lw 1
EOF

gnuplot -p <<EOF
  $(cat $prologue)
  set datafile separator ","
  set xrange [:625000]
  set xlabel "Time (msec)"
  # set y2tics
  set terminal pdf
  set output "fio-run-20th-sec.pdf"

  set ylabel "Latency (usec)"

  set title "fio run latency 4k, 1/20 sec"
  # set output 'fio-run-lat-4k-20ths.pdf'
  plot "lat-4k.log_clat.1.log" using 1:2 title "4k latency" ls 2 axes x1y1

  set title "fio run latency 16k, 1/20 sec"
  # set output 'fio-run-lat-16k-20ths.pdf'
  plot "lat-16k.log_clat.1.log" using 1:2 title "16k latency" ls 4 axes x1y1

  set title "fio run latency 64k, 1/20 sec"
  # set output 'fio-run-lat-64k-20ths.pdf'
  plot "lat-64k.log_clat.1.log" using 1:2 title "64k latency" ls 6 axes x1y1


  set ylabel "Bandwidth (KB/sec)"

  set title "fio run bandwidth 4k, 1/20 sec"
  # set output 'fio-run-bw-4k-20ths.pdf'
  plot "bw-4k.log_bw.1.log" using 1:2 title "4k bandwidth" ls 1

  set title "fio run bandwidth 16k, 1/20 sec"
  # set output 'fio-run-bw-16k-20ths.pdf'
  plot "bw-16k.log_bw.1.log" using 1:2 title "16k bandwidth" ls 3
  
  set title "fio run bandwidth 64k, 1/20 sec"
  # set output 'fio-run-bw-64k-20ths.pdf'
  plot "bw-64k.log_bw.1.log" using 1:2 title "64k bandwidth" ls 5
EOF

rm -f $prologue
