#!/bin/sh

# 4096 5793
# 8192 11585
# 16384 23170
# 32768 46341
# 65536 92682
# 131072 185364
# 262144 370728
# 524288 741455
# 1048576

# throttle=4096
# block_size=16384

run_time=300

error=0

for i in "$@" ;do
    case $i in
        --blocksize=*)
            block_size="${i#*=}"
            shift
            ;;
        --throttle=*)
            throttle="${i#*=}"
            shift
            ;;
        --time=*)
            run_time="${i#*=}"
            shift
            ;;
        *)
            echo "Unknown argument $i"
            error=1
            ;;
    esac
done

if [ $error -gt 0 ] ;then
    exit 1
fi

if [ -z "$throttle" -o -z "$blocksize" ] ;then
    echo "error: must provide both --throttle and --blocksize"
    exit 2
fi


sed -i --follow-symlinks "s,\(^[ \t]*bluestore_queue_max_bytes[ \t]*=[ \t]*\).*,\1${throttle}," ceph.conf


last_summary() {
  ls -tr regbench-summary* | tail -n 1
}

blocksize_dir="block-${block_size}"
throttle_dir="throttle-${throttle}"
dir=${blocksize_dir}/${throttle_dir}

mkdir -p $dir
for concurrent in 1 2 4 8 16 32 64 128 ;do
    run-regular-bench -b=${block_size} -c=${concurrent} -t=${run_time}
    mv $(last_summary) ${dir}/regbench-summary-t${throttle}-o-c${concurrent}.txt
done
