#!/bin/sh

if [ $# -ne 1 ] ; then
   echo Usage: $0 "<osdnum>"
   exit 1
fi

# pid=$(ps x | grep "build/bin/ceph-osd.*-i  *${1} " | cut -d' ' -f1)
# find process and extract its pid ; may be leading spaces if pid is low enough
pid=$(ps x | grep "build/bin/ceph-osd.*-i  *${1} " | \
	  sed "s/^ *\([0-9][0-9]*\).*/\1/")
echo found pid is $pid

if [ -n "$pid" ] ;then
    gdb bin/ceph $pid
else
    echo "Error: could not find a running ceph-osd process for osd $1."
    exit 2
fi
